<a href="https://colab.research.google.com/github/H20CH3PO2/grokking_algorithms/blob/main/09_dynamic_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

# 01_longest_common_subsequence
dp_table_blue =  ["b", "l", "u", "e", "a", "t"]
dp_table_clues = ["c", "l", "u", "e", "s", "t"]
dp_table = np.zeros((len(dp_table_blue), len(dp_table_clues))).T
print(dp_table)

for i in range(len(dp_table_blue)):
    for j in range(len(dp_table_clues)):
        if dp_table_clues[j] == dp_table_blue[i]:
            dp_table[j][i] = dp_table[j-1][i-1] + 1
        else:
            dp_table[j][i] = max(dp_table[j-1][i], dp_table[j][i-1])

print(dp_table)

print()

# 02_longest_common_substring
dp_table_blue =  ["b", "l", "u", "e", "a", "t"]
dp_table_clues = ["c", "l", "u", "e", "s", "t"]
dp_table = np.zeros((len(dp_table_blue), len(dp_table_clues))).T
print(dp_table)

for i in range(len(dp_table_blue)):
    for j in range(len(dp_table_clues)):
        if dp_table_clues[j] == dp_table_blue[i]:
            dp_table[j][i] = dp_table[j-1][i-1] + 1
        else:
            dp_table[j][i] = 0

print(dp_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2. 2.]
 [0. 1. 2. 3. 3. 3.]
 [0. 1. 2. 3. 3. 3.]
 [0. 1. 2. 3. 3. 4.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
